export PS1="[\u@\h \W]\\$ \[$(tput sgr0)\]"

alias vi=vim
alias tmuxn='tmux new-session -s'
alias mvntest='mvn test -Parq-wildfly-remote'
alias sshpi='ssh sahir@192.168.0.111'
alias mvncc='mvn clean compile'
alias mvnd='mvn wildfly:deploy'

export PATH="/snap/bin:$HOME/.local/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export PATH="/home/sahir/data/ide/node-v5.11.0-linux-x64/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin:$HOME/data/ide/eclipse"

export JAVA_HOME="$HOME/data/ide/jdk1.8.0_60"
export PATH="$PATH:$HOME/.local/bin"
export EDITOR=vim
export M2_HOME="$HOME/data/ide/apache-maven-3.3.3"
export PATH="$JAVA_HOME/bin:$M2_HOME/bin:$PATH"
export WORKON_HOME=~/data/venvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source $HOME/.local/bin/virtualenvwrapper.sh
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
alias cls='tput cup 15 0'
alias rmdockerps='docker rm $(docker ps -aq -f status=exited)'
alias rmdockerim='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Random cowsay with fortune
#if [ -x /usr/games/cowsay -a -x /usr/games/fortune ]; then
#    fortune | cowsay -f $(ls /usr/share/cowsay/cows/ | shuf -n1)
#fi

if [ -x /usr/bin/screenfetch ]; then
    screenfetch
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/sahir/.sdkman"
[[ -s "/home/sahir/.sdkman/bin/sdkman-init.sh" ]] && source "/home/sahir/.sdkman/bin/sdkman-init.sh"
