# source global bashrc
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PS1="[\u@\h \W]\\$ \[$(tput sgr0)\]"

alias vi=vim
alias tmuxn='tmux new-session -s'
alias mvntest='mvn test -Parq-wildfly-remote'
alias sshpi='ssh sahir@192.168.0.111'
alias mvncc='mvn clean compile'
alias mvnd='mvn wildfly:deploy'

export JAVA_HOME="/home/data/tools/sdkman/candidates/java/current"
export M2_HOME="/home/data/tools/sdkman/candidates/maven/current"
export EDITOR=vim
export WORKON_HOME=/home/data/venvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
#source /home/data/.local/bin/virtualenvwrapper.sh
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
alias cls='tput cup 15 0'
alias rmdockerps='docker rm $(docker ps -aq -f status=exited)'
alias rmdockerim='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'


export PATH="$JAVA_HOME/bin:$M2_HOME/bin:/home/data/tools/local/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"

# Random cowsay with fortune
#if [ -x /usr/games/cowsay -a -x /usr/games/fortune ]; then
#    fortune | cowsay -f $(ls /usr/share/cowsay/cows/ | shuf -n1)
#fi

if [ -x /usr/bin/screenfetch ]; then
    screenfetch
fi

[[ -s "/home/data/tools/rvm/scripts/rvm" ]] && source "/home/data/tools/rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="/home/data/tools/rvm/bin:$PATH" # Add RVM to PATH for scripting

export NVM_DIR="/home/data/tools/nvm"
[ -s $NVM_DIR/nvm.sh ] && source "$NVM_DIR/nvm.sh"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/data/tools/sdkman"
[[ -s "/home/data/tools/sdkman/bin/sdkman-init.sh" ]] && source "/home/data/tools/sdkman/bin/sdkman-init.sh"

source /home/sahir/.phpbrew/bashrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/data/tools/google-cloud-sdk/path.bash.inc' ]; then source '/home/data/tools/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/data/tools/google-cloud-sdk/completion.bash.inc' ]; then source '/home/data/tools/google-cloud-sdk/completion.bash.inc'; fi
