# Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="dpoggi"
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=30

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(emacs
        git
        docker
        git-flow
        gradle
        yarn)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh
# You may need to manually set your language environment
#PROMPT='%{$fg[green]%}(%M)% ${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
alias vi=vim
alias cls='tput cup 15 0'
alias rmdockerps='docker rm $(docker ps -aq -f status=exited)'
alias rmdockerim='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'

export PATH="/snap/bin:$HOME/.local/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

export JAVA_HOME="/home/data/tools/sdkman/candidates/java/current"
export M2_HOME="/home/data/tools/sdkman/candidates/maven/current"
export EDITOR=vim
export WORKON_HOME=/home/data/venvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
#source /home/data/.local/bin/virtualenvwrapper.sh
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PATH="$JAVA_HOME/bin:$M2_HOME/bin:/home/data/tools/local/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"

[[ -s "/home/data/tools/rvm/scripts/rvm" ]] && source "/home/data/tools/rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="/home/data/tools/rvm/bin:$PATH" # Add RVM to PATH for scripting

export NVM_DIR="/home/data/tools/nvm"
[ -s $NVM_DIR/nvm.sh ] && source "$NVM_DIR/nvm.sh"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/data/tools/sdkman"
[[ -s "/home/data/tools/sdkman/bin/sdkman-init.sh" ]] && source "/home/data/tools/sdkman/bin/sdkman-init.sh"

source /home/sahir/.phpbrew/bashrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/data/tools/google-cloud-sdk/path.zsh.inc' ]; then source '/home/data/tools/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/data/tools/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/data/tools/google-cloud-sdk/completion.zsh.inc'; fi

# Random cowsay with fortune
#if [ -x /usr/games/cowsay -a -x /usr/games/fortune ]; then
#    fortune | cowsay -f $(ls /usr/share/cowsay/cows/ | shuf -n1)
#fi

if [ -x /usr/bin/screenfetch ]; then
    screenfetch
fi

